### ISSUE TITLE
请问睡眠是否正常？

### ISSUE THREAD

**Issue by Kaijun** [NanjolnoRing/MSI-B450m-MORTAR-Hackintosh#1]
我自己做了一遍 EFI，发现睡眠一直有问题

USB 重新 Map 后还是不行

请教下 OP 是否已经解决了睡眠问题？能否参考下解法

**Comment by NanjolnoRing** [comment]
睡眠方面没有问题，正常唤醒，鼠标和键盘不要插到后面的USB3.0接口上！

**Comment by Kaijun** [comment]
> 睡眠方面没有问题，正常唤醒，鼠标和键盘不要插到后面的USB3.0接口上！

只能接到后面最上面两个 usb2 上是吗

**Comment by NanjolnoRing** [comment]
你试一下看看，睡眠情况有没有问题。能不能正常唤醒

**Comment by Kaijun** [comment]
@NanjolnoRing 不太行，进不去深度睡眠，我再看看啥问题谢谢

**Comment by Kaijun** [comment]
@NanjolnoRing BIOS 里关掉 IOMMU 后看起来能进睡眠了！

**Comment by Kaijun** [comment]
最终发现应该是 5600g 自带核显导致的睡眠不了

加上 -wegnoigpu 屏蔽 IGPU 就解决了

感谢！
